databases:
  - name: my-database
    plan: free
    databaseName: mydatabase
    user: myuser

services:
  - type: web
    name: my-web-api
    runtime: dotnet
    repo: https://github.com/Inamdjanof/TaxiCompany
    branch: main
    region: frankfurt
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/MyProject.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Host=my-database.internal;Port=5432;Database=mydatabase;Username=myuser;Password=yourpassword"



