services:
  - type: web
    name: taxicompany-api
    runtime: docker
    plan: free
    region: oregon  # O'zingizga mos regionni tanlang
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false  # Buni Render UI orqali qo'lda kiritish kerak
    dockerfilePath: ./src/TaxiCompany.API/Dockerfile
    autoDeploy: true
    healthCheckPath: "/health"

