databases:
  - name: my-database
    region: frankfurt
    plan: free
    databaseName: mydb
    user: myuser
    postgresMajorVersion: 15

services:
  - type: web
    name: my-web-api
    runtime: docker
    repo: https://github.com/Inamdjanof/TaxiCompany
    branch: main
    region: frankfurt
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: my-database
          property: connectionString

